// <auto-generated />
using System;
using System.Text.Json;
using Database.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415135440_submigr")]
    partial class submigr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.KeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ServerId", "Protocol");

                    b.ToTable("keys");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ProtocolConfigEntity", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("ExtraConfiguration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("ExtraPublicConfiguration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("Port")
                        .HasColumnType("bigint");

                    b.HasKey("ServerId", "Protocol");

                    b.ToTable("protocol_configs");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<long>("VpnLevel")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("rates");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Type");

                    b.ToTable("resources");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RoleAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ResourceId", "RoleId")
                        .IsUnique();

                    b.ToTable("role_assignments");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ServerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DawPort")
                        .HasColumnType("integer");

                    b.Property<string>("IpV4Address")
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("IpV6Address")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<int[]>("SupportedProtocols")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("servers");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.SubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PayedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevokableId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.KeyEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.ProtocolConfigEntity", "ProtocolConfig")
                        .WithMany()
                        .HasForeignKey("ServerId", "Protocol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProtocolConfig");

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ProtocolConfigEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ResourceEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Database.Infrastructure.Data.Entities.ResourceEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RoleAssignmentEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.ResourceEntity", "Resource")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.RoleEntity", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ServerEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.RateEntity", "Rate")
                        .WithMany()
                        .HasForeignKey("RateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.ResourceEntity", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rate");

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("Database.Infrastructure.Data.Entities.ResourceEntity", "Resource")
                        .WithOne()
                        .HasForeignKey("Database.Infrastructure.Data.Entities.UserEntity", "ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.ResourceEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Database.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
